version: '3.8'

services:
  bun-ide:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
      - "3000:3000"
    environment:
      - PASSWORD=${SERVICE_PASSWORD_CODE}
    volumes:
      - data:/home
    restart: unless-stopped

volumes:
  data: