version: "3.7"

services:
  jdownloader2:
    image: jlesage/jdownloader-2:v26.07.2
    restart: on-failure
    stop_grace_period: 1m
    security_opt:
      - seccomp:unconfined
    volumes:
      - jdownloader_config:/config:rw
      - jdownloader_output:/output:rw
      - /data/storage/downloads:/downloads 
    environment:
      - PUID=1000
      - PGID=1000
      - JDOWNLOADER_HEADLESS=
      - MYJDOWNLOADER_DEVICE_NAME=
      - MYJDOWNLOADER_EMAIL=
      - MYJDOWNLOADER_PASSWORD=
      - TZ=Europe/Istanbul
    ports:
      - "5800:5800"
      - "5900:5900"
      - "3129:3129"
    shm_size: "512mb"

volumes:
  jdownloader_config:
  jdownloader_output: