version: "3.8"

services:
  cncverse:
    image: budtmo/docker-android:emulator_11.0
    privileged: true

    devices:
      - /dev/kvm

    environment:
      EMULATOR_DEVICE: "Samsung Galaxy S10"
      WEB_VNC: "true"

    ports:
      - "6080:6080"
      - "5555:5555"

    volumes:
      - android-data:/home/androidusr

    restart: unless-stopped

volumes:
  android-data: